### ISSUE TITLE
How to use Buffer in uploadData parameter

### ISSUE THREAD

**Issue by janhox** [paul-wentworth/nodejs-ocr#1]
Hi,
thanks for this wrapper. Have tested a couple of scenarios but so far can only make it work with reading a file from local file system.

uploadData <string> or <Buffer> Image to be processed by API method.

I tried to point it to URL instead but that gives me err (File Not Found or Posted). 
I am now downloading my file into a buffer from that URL and passing into the processImage method but also getting back error.

TypeError: First argument must be a string or Buffer
    at write_ (_http_outgoing.js:655:11)
    at ClientRequest.write (_http_outgoing.js:630:10)
    at new Task (/Users/janhox/forza-io/scanman/abbyy1/node_modules/nodejs-ocr/index.js:43:52)
    at AbbyyClient._runApiMethod (/Users/janhox/forza-io/scanman/abbyy1/node_modules/nodejs-ocr/index.js:246:13)
    at AbbyyClient.processImage (/Users/janhox/forza-io/scanman/abbyy1/node_modules/nodejs-ocr/index.js:266:14)
    at abbyy1 (/Users/janhox/forza-io/scanman/abbyy1/index.js:38:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

I can see in my node api that the buffer I use is correct.
Do you have any tips or examples on how to pass buffer into the api ?

Thanks.

**Comment by janhox** [comment]
Got it working now, was an issue with my Buffer instance conversion.
